### ISSUE TITLE
NUC-UPS

### ISSUE THREAD

**Issue by chriswiggins** [mini-box/openups2#1]
If I change the productid to `0007` is this going to work with the NUC-UPS?

**Comment by connormcmk** [comment]
@chriswiggins did you try this and did it work?

**Comment by chriswiggins** [comment]
I didn't sorry @cnrmck 

Closing as I haven't got the need for it anymore

**Comment by adamcandy** [comment]
Yes @chriswiggins and @cnrmck -- this works with the NUC-UPS.  The NUT driver has been written to work on devices outside of the the d004 and d005.  I have been using this driver (version 0.4) successfully for a year or so with a NUC-UPS.  It is not fully supported, in that some parameters are not reported, but is good enough to work as a UPS and auto power down when needed.
